version: 2.1

orbs:
  node: circleci/node@5.2.0
  aws-cli: circleci/aws-cli@4.1.3

jobs:
  build:
    executor:
      name: node/default
      tag: '20.10.0'
    steps:
      - checkout
      - node/install-packages
      - run:
          name: "Build"
          command: "npm run build-lambda"
      - store_artifacts:
          path: ./dist
      - persist_to_workspace:
          root: ./dist
          paths:
            - '*'
  deploy:
    executor: 
      name: node/default
      tag: '20.10.0'
    steps:
      - checkout
      - node/install-packages
      - attach_workspace:
          at: ./dist
      - aws-cli/setup:
          profile_name: default
      - aws-cli/role_arn_setup:
          profile_name: circle-ci-dev
          role_arn: ${AWS_ROLE_ARN}
          source_profile: default
      - run:
          name: "Deploy"
          command: "npx cdk deploy"
        
workflows:
  lambda-build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build